### ISSUE TITLE
Expose SET options as part of API

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/sequelizer#6]
Jigsaw needs to know what DB options are set before running a study, so Sequelizer needs to expose this as part of its API.

**Comment by jenniferduryea** [comment]
@aguynamedryan How do we test for this?

**Comment by aguynamedryan** [comment]
This can't be tested directly.  If outcomesinsights/jigsaw#387 passes testing, this ticket can be closed out too.

**Comment by jenniferduryea** [comment]
Closing since outcomesinsights/jigsaw#387 was just closed.
